import { ensureDatabase } from "../../../../db/init";
import { assertSameOrigin, cleanText, errorResponse, getAdminContext, HttpError, readJson, writeAudit } from "../../../security";

export async function GET() {
  try { const context = await getAdminContext("finance.read"); if (!context) throw new HttpError(401, "Inicia sesión para continuar."); const db = await ensureDatabase(); const [plans, subscription] = await Promise.all([db.prepare("SELECT id,name,description,monthly_price_cents AS monthlyPriceCents,max_professionals AS maxProfessionals,max_appointments AS maxAppointments FROM plans WHERE active=1 ORDER BY monthly_price_cents").all(), db.prepare("SELECT s.id,s.plan_id AS planId,s.status,s.provider,s.current_period_start AS currentPeriodStart,s.current_period_end AS currentPeriodEnd,s.cancel_at_period_end AS cancelAtPeriodEnd,p.name AS planName,p.monthly_price_cents AS monthlyPriceCents,p.max_professionals AS maxProfessionals,p.max_appointments AS maxAppointments FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.business_id=?").bind(context.businessId).first()]); return Response.json({ plans: plans.results ?? [], subscription: subscription ?? null }, { headers: { "cache-control": "no-store" } }); } catch (error) { return errorResponse(error); }
}

export async function POST(request: Request) {
  try { assertSameOrigin(request); const context = await getAdminContext("settings.write"); if (!context) throw new HttpError(401, "Inicia sesión para continuar."); if (context.role !== "owner") throw new HttpError(403, "Solo el propietario puede cambiar el plan."); const body = await readJson<{ planId?: unknown }>(request, 2_048); const planId = cleanText(body.planId, 30); const db = await ensureDatabase(); const plan = await db.prepare("SELECT id FROM plans WHERE id=? AND active=1").bind(planId).first(); if (!plan) throw new HttpError(400, "Plan no válido."); const now = new Date(); const periodEnd = new Date(now.getTime() + 30 * 86_400_000).toISOString(); const current = await db.prepare("SELECT id FROM subscriptions WHERE business_id=?").bind(context.businessId).first<{ id:string }>(); const id = current?.id ?? crypto.randomUUID(); await db.prepare(`INSERT INTO subscriptions (id,business_id,plan_id,status,provider,current_period_start,current_period_end,cancel_at_period_end,created_at) VALUES (?,?,?,'active','manual',?,?,0,?) ON CONFLICT(business_id) DO UPDATE SET plan_id=excluded.plan_id,status='active',current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,cancel_at_period_end=0`).bind(id, context.businessId, planId, now.toISOString(), periodEnd, now.toISOString()).run(); await writeAudit(db, { businessId: context.businessId, user: context.user, action: "subscription.plan_changed", entityType: "subscription", entityId: id, metadata: { planId } }); return Response.json({ ok: true, planId, status: "active" }, { headers: { "cache-control": "no-store" } }); } catch (error) { return errorResponse(error); }
}
