"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, Scissors, ShieldCheck, Sparkles, UserRound } from "lucide-react";

type Service = { id:string; name:string; category:string; durationMinutes:number; priceCents:number };
type Professional = { id:string; name:string; specialty:string };
export type BookingCatalog = { business:{name:string;slug:string;timezone:string;currency:string};services:Service[];professionals:Professional[] };

function isoAfter(days:number){const date=new Date();date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function money(cents:number,currency:string){return new Intl.NumberFormat("es-VE",{style:"currency",currency}).format(cents/100)}

export function BookingApp({slug,initialCatalog}:{slug:string;initialCatalog:BookingCatalog|null}){
  const [catalog,setCatalog]=useState<BookingCatalog|null>(initialCatalog); const [loadingError,setLoadingError]=useState("");
  const [step,setStep]=useState(0); const [serviceId,setServiceId]=useState(initialCatalog?.services[0]?.id??""); const [professionalId,setProfessionalId]=useState(initialCatalog?.professionals[0]?.id??"");
  const [date,setDate]=useState(()=>isoAfter(1)); const [time,setTime]=useState(""); const [times,setTimes]=useState<string[]>([]); const [loadingTimes,setLoadingTimes]=useState(false);
  const [done,setDone]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const formStartedAt=useRef(0); const idempotencyKey=useRef("");

  useEffect(()=>{if(initialCatalog)return;fetch(`/api/public/catalog?slug=${encodeURIComponent(slug)}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setCatalog(body);setServiceId(body.services[0]?.id??"");setProfessionalId(body.professionals[0]?.id??"");setLoadingTimes(true)}).catch(reason=>setLoadingError(reason instanceof Error?reason.message:"No pudimos cargar esta barbería"))},[slug,initialCatalog]);
  useEffect(()=>{if(!catalog||!serviceId||!professionalId||!date)return;fetch(`/api/public/availability?slug=${encodeURIComponent(slug)}&serviceId=${encodeURIComponent(serviceId)}&professionalId=${encodeURIComponent(professionalId)}&date=${date}`).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);const nextTimes=Array.isArray(body.times)?body.times:[];setTimes(nextTimes);setTime(current=>nextTimes.includes(current)?current:(nextTimes[0]??""))}).catch(reason=>{setTimes([]);setTime("");setError(reason instanceof Error?reason.message:"No pudimos consultar la disponibilidad")}).finally(()=>setLoadingTimes(false))},[catalog,serviceId,professionalId,date,slug]);

  const dates=useMemo(()=>Array.from({length:8},(_,index)=>{const iso=isoAfter(index);const parsed=new Date(`${iso}T12:00:00Z`);return{iso,day:new Intl.DateTimeFormat("es-VE",{weekday:"short",timeZone:"UTC"}).format(parsed).replace(".",""),num:iso.slice(8),month:new Intl.DateTimeFormat("es-VE",{month:"short",timeZone:"UTC"}).format(parsed)}}),[]);
  const service=catalog?.services.find(item=>item.id===serviceId)??catalog?.services[0]; const professional=catalog?.professionals.find(item=>item.id===professionalId)??catalog?.professionals[0];
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!service||!professional||!time)return;setSaving(true);setError("");const form=new FormData(e.currentTarget);if(!idempotencyKey.current)idempotencyKey.current=crypto.randomUUID();try{const response=await fetch("/api/public/bookings",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json","idempotency-key":idempotencyKey.current},body:JSON.stringify({...Object.fromEntries(form.entries()),slug,serviceId,professionalId,date,time,formStartedAt:formStartedAt.current})});const body=await response.json();if(!response.ok)throw new Error(body.error);setDone(true)}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos confirmar");setSaving(false)}};

  if(loadingError)return <div className="booking-site"><BookingHeader name="Corteza"/><main className="success-card"><span className="eyebrow">Reserva segura</span><h1>No encontramos esta barbería.</h1><p>{loadingError}</p></main></div>;
  if(!catalog||!service||!professional)return <div className="booking-loading"><Scissors/><strong>Cargando agenda segura…</strong></div>;
  if(done)return <div className="booking-site"><BookingHeader name={catalog.business.name}/><main className="success-card"><div className="success-check"><Check/></div><span className="eyebrow">Reserva confirmada</span><h1>Nos vemos pronto.</h1><p>Tu cita quedó guardada. Conserva esta pantalla como confirmación.</p><div className="receipt"><div><span>Servicio</span><strong>{service.name}</strong></div><div><span>Fecha y hora</span><strong>{formatDate(date)} · {time}</strong></div><div><span>Profesional</span><strong>{professional.name}</strong></div><div><span>Total</span><strong>{money(service.priceCents,catalog.business.currency)}</strong></div></div><button className="booking-primary" onClick={()=>{setDone(false);setStep(0);setSaving(false);idempotencyKey.current="";formStartedAt.current=Date.now()}}>Hacer otra reserva</button></main><BookingFooter name={catalog.business.name}/></div>;
  const begin=()=>{formStartedAt.current=Date.now();setStep(1)}; const chooseService=(id:string)=>{formStartedAt.current ||= Date.now();setServiceId(id);setLoadingTimes(true);setError("");setStep(2)}; const chooseDate=(value:string)=>{setLoadingTimes(true);setError("");setDate(value)};
  return <div className="booking-site"><BookingHeader name={catalog.business.name}/>{step===0?<Landing services={catalog.services} currency={catalog.business.currency} onStart={begin} onSelect={chooseService}/>:<main className="booking-flow"><div className="booking-progress">{["Servicio","Fecha y hora","Tus datos"].map((label,index)=><div className={index<step?"active":""} key={label}><span>{index<step?<Check size={15}/>:index+1}</span><b>{label}</b></div>)}</div><div className="flow-card">{step===1&&<ServiceStep services={catalog.services} currency={catalog.business.currency} selected={serviceId} onSelect={(id)=>{setServiceId(id);setLoadingTimes(true);setError("")}}/>} {step===2&&<DateStep dates={dates} date={date} setDate={chooseDate} time={time} setTime={setTime} times={times} loading={loadingTimes} professional={professional}/>} {step===3&&<DetailsStep service={service} professional={professional} currency={catalog.business.currency} date={date} time={time} onSubmit={submit} saving={saving} error={error}/>}<div className="flow-actions">{step>1?<button type="button" className="booking-back" onClick={()=>setStep(step-1)}><ArrowLeft/> Atrás</button>:<button type="button" className="booking-back" onClick={()=>setStep(0)}><ArrowLeft/> Inicio</button>}{step<3&&<button type="button" className="booking-primary" disabled={step===2&&!time} onClick={()=>setStep(step+1)}>Continuar <ArrowRight/></button>}</div></div></main>}<BookingFooter name={catalog.business.name}/></div>
}

function BookingHeader({name}:{name:string}){return <header className="booking-header"><div className="booking-brand"><span><Scissors/></span><div><strong>{name.toUpperCase()}</strong><small>RESERVAS ONLINE</small></div></div><div className="secure-booking"><ShieldCheck/><span>Conexión y reserva protegidas</span></div></header>}
function Landing({services,currency,onStart,onSelect}:{services:Service[];currency:string;onStart:()=>void;onSelect:(id:string)=>void}){return <><section className="booking-hero"><div className="hero-noise"/><div className="hero-copy"><span className="hero-pill"><Sparkles/> Reservas online 24/7</span><h1>Tu mejor versión<br/><em>empieza aquí.</em></h1><p>Elige un servicio, consulta disponibilidad real y confirma sin esperas.</p><button className="booking-primary large" onClick={onStart}>Reservar ahora <ArrowRight/></button><div className="hero-proof"><span><ShieldCheck/>Seguro</span><p>Validación de disponibilidad en tiempo real</p></div></div><div className="hero-visual"><div className="poster-card"><span>AGENDA ONLINE</span><div className="poster-scissors"><Scissors/></div><strong>CORTEZA</strong><small>PRECISIÓN · CARÁCTER · CONFIANZA</small></div><div className="floating-note"><Clock3/><div><b>Sin dobles reservas</b><span>Bloqueo atómico del horario</span></div></div></div></section><section className="booking-services"><div className="section-intro"><span className="eyebrow">Servicios disponibles</span><h2>Elige tu experiencia</h2><p>Precio y duración confirmados por la barbería.</p></div><div className="public-service-grid">{services.map((service,index)=><button type="button" className="public-service-card" onClick={()=>onSelect(service.id)} key={service.id}><div className={`public-service-art ${["copper","olive","ink"][index%3]}`}><span>{String(index+1).padStart(2,"0")}</span><Scissors/></div><div><span className="category">{service.category}</span><h3>{service.name}</h3><p>Servicio profesional con disponibilidad en tiempo real.</p><footer><span><Clock3/>{service.durationMinutes} min</span><strong>{money(service.priceCents,currency)}</strong></footer></div></button>)}</div></section><section className="trust-strip"><div><ShieldCheck/><strong>Confirmación inmediata</strong><span>Bloqueo seguro de tu horario</span></div><div><UserRound/><strong>Datos mínimos</strong><span>Solo pedimos lo necesario</span></div><div><CalendarDays/><strong>Disponibilidad real</strong><span>Horarios calculados desde la agenda</span></div></section></>}
function ServiceStep({services,currency,selected,onSelect}:{services:Service[];currency:string;selected:string;onSelect:(value:string)=>void}){return <div><span className="eyebrow">Paso 1</span><h1>¿Qué te gustaría reservar?</h1><p className="flow-subtitle">Selecciona un servicio para consultar la disponibilidad.</p><div className="flow-services">{services.map((service,index)=><button type="button" className={selected===service.id?"selected":""} onClick={()=>onSelect(service.id)} key={service.id}><div className={`mini-art ${["copper","olive","ink"][index%3]}`}><Scissors/></div><div><strong>{service.name}</strong><span>{service.category}</span><small><Clock3/>{service.durationMinutes} min</small></div><b>{money(service.priceCents,currency)}</b>{selected===service.id&&<i><Check/></i>}</button>)}</div></div>}
function DateStep({dates,date,setDate,time,setTime,times,loading,professional}:{dates:{iso:string;day:string;num:string;month:string}[];date:string;setDate:(value:string)=>void;time:string;setTime:(value:string)=>void;times:string[];loading:boolean;professional:Professional}){return <div><span className="eyebrow">Paso 2</span><h1>Elige fecha y hora</h1><p className="flow-subtitle">Disponibilidad con {professional.name}.</p><h3 className="flow-label">Próximos días</h3><div className="date-strip">{dates.map(item=><button type="button" className={date===item.iso?"selected":""} onClick={()=>setDate(item.iso)} key={item.iso}><span>{item.day}</span><strong>{item.num}</strong><small>{item.month}</small></button>)}</div><h3 className="flow-label">Horarios disponibles</h3>{loading?<div className="availability-note">Consultando agenda…</div>:times.length?<div className="time-grid">{times.map(item=><button type="button" className={time===item?"selected":""} onClick={()=>setTime(item)} key={item}>{item}</button>)}</div>:<div className="availability-note">No quedan horarios para este día. Prueba otra fecha.</div>}</div>}
function DetailsStep({service,professional,currency,date,time,onSubmit,saving,error}:{service:Service;professional:Professional;currency:string;date:string;time:string;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void;saving:boolean;error:string}){return <div><span className="eyebrow">Último paso</span><h1>Completa tus datos</h1><p className="flow-subtitle">Se usarán únicamente para gestionar esta cita.</p><div className="booking-summary"><div><Scissors/><span>{service.name}<small>{service.durationMinutes} min · {professional.name}</small></span></div><div><CalendarDays/><span>{formatDate(date)}<small>{time}</small></span></div><strong>{money(service.priceCents,currency)}</strong></div><form className="booking-form" onSubmit={onSubmit}><label>Nombre completo<input name="name" required maxLength={100} autoComplete="name" placeholder="Tu nombre"/></label><label>WhatsApp / teléfono<input name="phone" required maxLength={25} autoComplete="tel" placeholder="+58 412 000 0000"/></label><label className="wide">Email<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="tu@email.com"/></label><label className="wide">Notas <span>(opcional)</span><textarea name="notes" maxLength={500} placeholder="¿Algo que debamos saber?"/></label><label className="honeypot" aria-hidden="true">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label>{error&&<p className="form-error wide" role="alert">{error}</p>}<button className="booking-primary wide submit-booking" disabled={saving||!time}>{saving?"Confirmando…":`Confirmar reserva · ${money(service.priceCents,currency)}`}</button></form></div>}
function BookingFooter({name}:{name:string}){return <footer className="booking-footer"><div className="booking-brand"><span><Scissors/></span><div><strong>{name.toUpperCase()}</strong><small>RESERVAS ONLINE</small></div></div><p>© 2026 · Privacidad por diseño</p><span><ShieldCheck size={13}/> Reserva protegida</span></footer>}
function formatDate(value:string){return new Intl.DateTimeFormat("es-VE",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}
