"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, MapPin, Scissors, ShieldCheck, Sparkles, Star, UserRound } from "lucide-react";

const services = [
  { id:"svc_corte", name:"Corte Signature", category:"Cortes", duration:35, price:18, description:"Técnica, textura y acabado adaptado a tu estilo.", tone:"copper" },
  { id:"svc_barba", name:"Barba Ritual", category:"Barba", duration:25, price:12, description:"Perfilado, vapor caliente y cuidado de la piel.", tone:"olive" },
  { id:"svc_combo", name:"Corte + Barba", category:"Experiencia", duration:55, price:28, description:"La experiencia completa para salir impecable.", tone:"ink" },
];
const times=["09:00","09:30","10:00","10:30","11:30","12:00","14:00","14:30","15:30","16:00","17:00","18:00"];

export function BookingApp({slug}:{slug:string}){
  const [step,setStep]=useState(0); const [serviceId,setServiceId]=useState("svc_corte"); const [date,setDate]=useState("2026-08-03"); const [time,setTime]=useState("10:30"); const [done,setDone]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const service=services.find(s=>s.id===serviceId)!;
  const dates=useMemo(()=>[{iso:"2026-08-03",day:"Lun",num:"03"},{iso:"2026-08-04",day:"Mar",num:"04"},{iso:"2026-08-05",day:"Mié",num:"05"},{iso:"2026-08-06",day:"Jue",num:"06"},{iso:"2026-08-07",day:"Vie",num:"07"},{iso:"2026-08-08",day:"Sáb",num:"08"}],[]);
  const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget);try{const r=await fetch("/api/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(form.entries()),serviceId,professionalId:"pro_mateo",date,time,source:"online"})});const data=await r.json();if(!r.ok)throw new Error(data.error);setDone(true);}catch(err){setError(err instanceof Error?err.message:"No pudimos confirmar");setSaving(false)}};
  if(done)return <div className="booking-site"><BookingHeader/><main className="success-card"><div className="success-check"><Check/></div><span className="eyebrow">Reserva confirmada</span><h1>Nos vemos pronto.</h1><p>Tu cita quedó agendada en Corteza Studio. Te enviaremos un recordatorio antes de la hora.</p><div className="receipt"><div><span>Servicio</span><strong>{service.name}</strong></div><div><span>Fecha y hora</span><strong>3 de agosto · {time}</strong></div><div><span>Profesional</span><strong>Mateo Silva</strong></div><div><span>Total</span><strong>${service.price}.00</strong></div></div><button className="booking-primary" onClick={()=>{setDone(false);setStep(0);setSaving(false)}}>Hacer otra reserva</button></main><BookingFooter/></div>;
  return <div className="booking-site"><BookingHeader/>{step===0?<Landing onStart={()=>setStep(1)} onSelect={(id)=>{setServiceId(id);setStep(2)}}/>:<main className="booking-flow"><div className="booking-progress">{["Servicio","Fecha y hora","Tus datos"].map((label,i)=><div className={i<step?"active":""} key={label}><span>{i<step?<Check size={15}/>:i+1}</span><b>{label}</b></div>)}</div><div className="flow-card">{step===1&&<ServiceStep selected={serviceId} onSelect={setServiceId}/>} {step===2&&<DateStep dates={dates} date={date} setDate={setDate} time={time} setTime={setTime}/>} {step===3&&<DetailsStep service={service} date={date} time={time} onSubmit={submit} saving={saving} error={error}/>}<div className="flow-actions">{step>1?<button className="booking-back" onClick={()=>setStep(step-1)}><ArrowLeft/> Atrás</button>:<button className="booking-back" onClick={()=>setStep(0)}><ArrowLeft/> Inicio</button>}{step<3&&<button className="booking-primary" onClick={()=>setStep(step+1)}>Continuar <ArrowRight/></button>}</div></div></main>}<BookingFooter/></div>
}

function BookingHeader(){return <header className="booking-header"><div className="booking-brand"><span><Scissors/></span><div><strong>CORTEZA</strong><small>BARBER STUDIO</small></div></div><div className="booking-location"><MapPin/><span>Av. Principal, Caracas</span></div><a href="tel:+584125550184">+58 412 555 0184</a></header>}
function Landing({onStart,onSelect}:{onStart:()=>void;onSelect:(id:string)=>void}){return <><section className="booking-hero"><div className="hero-noise"/><div className="hero-copy"><span className="hero-pill"><Sparkles/> Reservas online 24/7</span><h1>Tu mejor versión<br/><em>empieza aquí.</em></h1><p>Cortes precisos, rituales de barba y una experiencia diseñada alrededor de ti.</p><button className="booking-primary large" onClick={onStart}>Reservar ahora <ArrowRight/></button><div className="hero-proof"><span><Star fill="currentColor"/>4.9</span><p>Más de 800 clientes satisfechos</p></div></div><div className="hero-visual"><div className="poster-card"><span>EST. 2024</span><div className="poster-scissors"><Scissors/></div><strong>CORTEZA</strong><small>CRAFT · CHARACTER · CONFIDENCE</small></div><div className="floating-note"><Clock3/><div><b>Sin esperas</b><span>Elige tu hora online</span></div></div></div></section><section className="booking-services" id="servicios"><div className="section-intro"><span className="eyebrow">Nuestros servicios</span><h2>Elige tu experiencia</h2><p>Cada servicio incluye consulta de estilo y acabado profesional.</p></div><div className="public-service-grid">{services.map((s,i)=><button className="public-service-card" onClick={()=>onSelect(s.id)} key={s.id}><div className={`public-service-art ${s.tone}`}><span>0{i+1}</span><Scissors/></div><div><span className="category">{s.category}</span><h3>{s.name}</h3><p>{s.description}</p><footer><span><Clock3/>{s.duration} min</span><strong>${s.price}</strong></footer></div></button>)}</div></section><section className="trust-strip"><div><ShieldCheck/><strong>Confirmación inmediata</strong><span>Tu cita queda lista al instante</span></div><div><UserRound/><strong>Profesionales expertos</strong><span>Técnica y atención personalizada</span></div><div><CalendarDays/><strong>Cambios sencillos</strong><span>Gestiona tu reserva sin llamadas</span></div></section></>}
function ServiceStep({selected,onSelect}:{selected:string;onSelect:(v:string)=>void}){return <div><span className="eyebrow">Paso 1</span><h1>¿Qué te gustaría reservar?</h1><p className="flow-subtitle">Selecciona un servicio para ver la disponibilidad.</p><div className="flow-services">{services.map(s=><button className={selected===s.id?"selected":""} onClick={()=>onSelect(s.id)} key={s.id}><div className={`mini-art ${s.tone}`}><Scissors/></div><div><strong>{s.name}</strong><span>{s.description}</span><small><Clock3/>{s.duration} min</small></div><b>${s.price}</b>{selected===s.id&&<i><Check/></i>}</button>)}</div></div>}
function DateStep({dates,date,setDate,time,setTime}:{dates:{iso:string;day:string;num:string}[];date:string;setDate:(v:string)=>void;time:string;setTime:(v:string)=>void}){return <div><span className="eyebrow">Paso 2</span><h1>Elige fecha y hora</h1><p className="flow-subtitle">Horarios disponibles con Mateo Silva.</p><h3 className="flow-label">Agosto 2026</h3><div className="date-strip">{dates.map(d=><button className={date===d.iso?"selected":""} onClick={()=>setDate(d.iso)} key={d.iso}><span>{d.day}</span><strong>{d.num}</strong></button>)}</div><h3 className="flow-label">Horarios disponibles</h3><div className="time-grid">{times.map(t=><button className={time===t?"selected":""} onClick={()=>setTime(t)} key={t}>{t}</button>)}</div></div>}
function DetailsStep({service,date,time,onSubmit,saving,error}:{service:typeof services[number];date:string;time:string;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;saving:boolean;error:string}){return <div><span className="eyebrow">Último paso</span><h1>Completa tus datos</h1><p className="flow-subtitle">Te enviaremos la confirmación y el recordatorio.</p><div className="booking-summary"><div><Scissors/><span>{service.name}<small>{service.duration} min · Mateo Silva</small></span></div><div><CalendarDays/><span>3 de agosto<small>{time} · Corteza Studio</small></span></div><strong>${service.price}.00</strong></div><form className="booking-form" onSubmit={onSubmit}><label>Nombre completo<input name="name" required placeholder="Tu nombre"/></label><label>WhatsApp / teléfono<input name="phone" required placeholder="+58 412 000 0000"/></label><label className="wide">Email<input name="email" type="email" required placeholder="tu@email.com"/></label><label className="wide">Notas <span>(opcional)</span><textarea name="notes" placeholder="¿Algo que debamos saber?"/></label>{error&&<p className="form-error wide">{error}</p>}<button className="booking-primary wide submit-booking" disabled={saving}>{saving?"Confirmando...":`Confirmar reserva · $${service.price}.00`}</button></form></div>}
function BookingFooter(){return <footer className="booking-footer"><div className="booking-brand"><span><Scissors/></span><div><strong>CORTEZA</strong><small>BARBER STUDIO</small></div></div><p>© 2026 Corteza Studio · Caracas, Venezuela</p><span>Reservas seguras por Corteza</span></footer>}
