"use client";

import { useEffect, useState } from "react";
import { Boxes, FileText, Minus, PackagePlus, Plus, Printer, ReceiptText, RotateCcw, ShoppingCart, WalletCards } from "lucide-react";
import { apiError, isJsonObject, readJsonObject } from "./api-json";
import { CashManager as CashManagerFallback } from "./CashManager";

type Product = { id:string;name:string;sku:string;category:string;priceCents:number;costCents:number;stockQuantity:number;minimumStock:number;active:number|boolean };
type CartLine = { product:Product; quantity:number };
type CommerceData = { products:Product[];movements:Record<string,unknown>[];expenses:Record<string,unknown>[];sales:Record<string,unknown>[];refunds:Record<string,unknown>[];payments:Record<string,unknown>[];summary:Record<string,number>;canManage:boolean };
type CashAppointment = { id:string;date:string;time:string;status:string;totalCents:number;paidCents:number;paymentStatus:string;clientName:string;serviceName:string };

export function CommerceManager({ appointments, onPaymentChanged }:{ appointments:CashAppointment[];onPaymentChanged:(appointmentId:string,paidCents:number,totalCents?:number)=>void }) {
  const [tab,setTab]=useState("caja");
  const [data,setData]=useState<CommerceData|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const refresh=async()=>{const response=await fetch("/api/admin/commerce",{credentials:"same-origin"});const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos cargar la operación comercial"));setData(parseData(body));};
  useEffect(()=>{let active=true;fetch("/api/admin/commerce",{credentials:"same-origin"}).then(async(response)=>{const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos cargar la operación comercial"));if(active)setData(parseData(body))}).catch((reason)=>{if(active)setError(reason instanceof Error?reason.message:"No pudimos cargar la operación comercial")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const request=async(payload:Record<string,unknown>)=>{setSaving(true);setError("");setMessage("");try{const response=await fetch("/api/admin/commerce",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos guardar la operación"));await refresh();return body}finally{setSaving(false)}};
  const setStatus=(next:string)=>{setTab(next);setError("");setMessage("")};
  if(loading&&!data)return <div className="commerce-stack"><div className="loading-line"/></div>;
  return <div className="commerce-stack">
    {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success">{message}</p>}
    <div className="commerce-tabs" role="tablist">{[["caja","Caja",WalletCards],["pos","POS",ShoppingCart],["inventario","Inventario",Boxes],["gastos","Gastos",ReceiptText],["reembolsos","Reembolsos",RotateCcw],["recibos","Recibos",FileText]].map(([id,label,Icon])=><button key={id as string} className={tab===id?"active":""} onClick={()=>setStatus(id as string)} role="tab" aria-selected={tab===id}><Icon size={15}/>{label as string}</button>)}</div>
    {tab==="caja"&&<CashPanel appointments={appointments} onPaymentChanged={onPaymentChanged}/>} {tab==="pos"&&<PosPanel data={data!} saving={saving} request={request} onMessage={setMessage}/>} {tab==="inventario"&&<InventoryPanel data={data!} saving={saving} request={request} onMessage={setMessage}/>} {tab==="gastos"&&<ExpensePanel data={data!} saving={saving} request={request} onMessage={setMessage}/>} {tab==="reembolsos"&&<RefundPanel data={data!} saving={saving} request={request} onMessage={setMessage} onPaymentChanged={onPaymentChanged}/>} {tab==="recibos"&&<ReceiptPanel appointments={appointments} sales={data?.sales??[]}/>} 
  </div>;
}

function CashPanel({appointments,onPaymentChanged}:{appointments:CashAppointment[];onPaymentChanged:(appointmentId:string,paidCents:number,totalCents?:number)=>void}){ return <CashManagerFallback appointments={appointments} onPaymentChanged={onPaymentChanged}/>; }

function PosPanel({data,saving,request,onMessage}:{data:CommerceData;saving:boolean;request:(payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;onMessage:(value:string)=>void}){
  const [cart,setCart]=useState<CartLine[]>([]);const [method,setMethod]=useState("efectivo");const [tip,setTip]=useState("0");const [discount,setDiscount]=useState("0");const [promoCode,setPromoCode]=useState("");
  const subtotal=cart.reduce((sum,line)=>sum+line.product.priceCents*line.quantity,0);const discountCents=Math.min(subtotal,Math.max(0,Math.round(Number(discount||0)*100)));const tipCents=Math.max(0,Math.round(Number(tip||0)*100));
  const add=(product:Product)=>setCart((lines)=>{const existing=lines.find((line)=>line.product.id===product.id);if(existing)return lines.map((line)=>line.product.id===product.id?{...line,quantity:Math.min(product.stockQuantity,line.quantity+1)}:line);return product.stockQuantity>0?[...lines,{product,quantity:1}]:lines});
  const submit=async()=>{if(!cart.length)return;try{const body=await request({action:"sale",items:cart.map((line)=>({productId:line.product.id,quantity:line.quantity})),method,tipCents,discountCents,promoCode:promoCode.trim()});setCart([]);setTip("0");setDiscount("0");setPromoCode("");const promoApplied=typeof body.promoDiscountCents==="number"&&body.promoDiscountCents>0?` Promoción aplicada: -${money(body.promoDiscountCents)}.`:"";onMessage(`Venta registrada y stock actualizado.${promoApplied}`);if(typeof body.id==="string")window.open(`/api/admin/receipts?saleId=${encodeURIComponent(body.id)}`,"_blank","noopener,noreferrer")}catch{/* parent displays the request error */}};
  return <div className="commerce-grid"><section className="panel commerce-products"><div className="panel-title"><div><h2>Productos</h2><p>Selecciona artículos para crear una venta de mostrador.</p></div></div><div className="product-picker">{data.products.filter((product)=>product.active!==0&&product.stockQuantity>0).map((product)=><button className="product-tile" key={product.id} onClick={()=>add(product)}><span>{product.category}</span><strong>{product.name}</strong><small>{product.stockQuantity} disponibles</small><b>{money(product.priceCents)}</b></button>)}{!data.products.some((product)=>product.active!==0&&product.stockQuantity>0)&&<Empty text="No hay productos con stock disponible."/>}</div></section><section className="panel pos-cart"><div className="panel-title"><div><h2>Venta actual</h2><p>{cart.length} productos en el carrito</p></div><ShoppingCart size={20}/></div>{cart.map((line)=><div className="cart-row" key={line.product.id}><div><strong>{line.product.name}</strong><small>{money(line.product.priceCents)} c/u</small></div><div className="quantity"><button onClick={()=>setCart((items)=>items.flatMap((item)=>item.product.id===line.product.id?(item.quantity>1?[{...item,quantity:item.quantity-1}]:[]):[item]))}><Minus size={13}/></button><b>{line.quantity}</b><button onClick={()=>add(line.product)}><Plus size={13}/></button></div><strong>{money(line.product.priceCents*line.quantity)}</strong></div>)}{!cart.length&&<Empty text="Agrega productos para comenzar."/>}<div className="pos-totals"><label>Descuento<input type="number" min="0" step="0.01" value={discount} onChange={(event)=>setDiscount(event.target.value)}/></label><label>Propina<input type="number" min="0" step="0.01" value={tip} onChange={(event)=>setTip(event.target.value)}/></label><label className="wide">Código promocional<input value={promoCode} onChange={(event)=>setPromoCode(event.target.value.toUpperCase())} maxLength={32} placeholder="Ej. BIENVENIDO10"/></label><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Total</span><b>{money(subtotal-discountCents)}</b></div><select value={method} onChange={(event)=>setMethod(event.target.value)}><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="transferencia">Transferencia</option><option value="pago_movil">Pago móvil</option></select><button className="primary" disabled={!cart.length||saving} onClick={()=>void submit()}>{saving?"Guardando...":"Cobrar venta"}</button></div></section></div>;
}

function InventoryPanel({data,saving,request,onMessage}:{data:CommerceData;saving:boolean;request:(payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;onMessage:(value:string)=>void}){
  const [adding,setAdding]=useState(false);const [editing,setEditing]=useState<Product|null>(null);const [adjusting,setAdjusting]=useState<Product|null>(null);const submitProduct=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await request({action:editing?"product_update":"product",id:editing?.id,name:form.get("name"),sku:form.get("sku"),category:form.get("category"),priceCents:cents(form.get("price")),costCents:cents(form.get("cost")),stockQuantity:whole(form.get("stock")),minimumStock:whole(form.get("minimum")),active:form.get("active")==="on"});setAdding(false);setEditing(null);onMessage(editing?"Producto actualizado.":"Producto creado.")}catch{} };
  return <div className="panel inventory-panel"><div className="panel-title"><div><h2>Inventario</h2><p>Control de existencias, mínimos y movimientos.</p></div><button className="primary compact" onClick={()=>setAdding(true)}><PackagePlus size={15}/> Producto</button></div><div className="inventory-table"><div className="inventory-head"><span>Producto</span><span>Precio</span><span>Stock</span><span>Estado</span><span/></div>{data.products.map((product)=><div className="inventory-row" key={product.id}><span data-label="Producto"><strong>{product.name}</strong><small>{product.category}{product.sku?` · ${product.sku}`:""}</small></span><b data-label="Precio">{money(product.priceCents)}</b><strong data-label="Stock" className={product.stockQuantity<=product.minimumStock?"stock-low":""}>{product.stockQuantity}</strong><span data-label="Estado" className={`status ${product.active!==0?"confirmada":"cancelada"}`}>{product.active!==0?(product.stockQuantity<=product.minimumStock?"Stock bajo":"Activo"):"Inactivo"}</span><span className="inventory-actions"><button className="secondary compact" onClick={()=>setEditing(product)}>Editar</button><button className="secondary compact" onClick={()=>setAdjusting(product)}>Ajustar</button></span></div>)}{!data.products.length&&<Empty text="Todavía no hay productos."/>}</div>{(adding||editing)&&<ProductModal product={editing??undefined} saving={saving} onClose={()=>{setAdding(false);setEditing(null)}} onSubmit={submitProduct}/>} {adjusting&&<AdjustModal product={adjusting} saving={saving} onClose={()=>setAdjusting(null)} onSubmit={async(delta,type,note)=>{try{await request({action:"inventory",productId:adjusting.id,deltaQuantity:delta,type,note});setAdjusting(null);onMessage("Inventario actualizado.")}catch{}}}/>}</div>;
}

function ExpensePanel({data,saving,request,onMessage}:{data:CommerceData;saving:boolean;request:(payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;onMessage:(value:string)=>void}){const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{await request({action:"expense",category:form.get("category"),description:form.get("description"),vendor:form.get("vendor"),amountCents:cents(form.get("amount")),method:form.get("method"),receiptNumber:form.get("receiptNumber"),notes:form.get("notes")});event.currentTarget.reset();onMessage("Gasto registrado en la caja.")}catch{}};return <div className="commerce-grid"><form className="panel expense-form" onSubmit={submit}><div className="panel-title"><div><h2>Registrar gasto</h2><p>Todo egreso queda trazado y afecta el arqueo.</p></div></div><div className="form-grid"><label>Categoría<select name="category" defaultValue="insumos"><option value="insumos">Insumos</option><option value="alquiler">Alquiler</option><option value="servicios">Servicios</option><option value="nómina">Nómina</option><option value="otro">Otro</option></select></label><label>Monto<input name="amount" type="number" min="0.01" step="0.01" required/></label><label className="wide">Descripción<input name="description" maxLength={180} placeholder="Ej. Navajas y desinfectante" required/></label><label>Proveedor<input name="vendor" maxLength={120}/></label><label>Método<select name="method" defaultValue="efectivo"><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="transferencia">Transferencia</option><option value="pago_movil">Pago móvil</option></select></label><label>Comprobante<input name="receiptNumber" maxLength={80}/></label><label className="wide">Notas<textarea name="notes" maxLength={500}/></label></div><button className="primary" disabled={saving}>{saving?"Guardando...":"Registrar gasto"}</button></form><section className="panel expense-list"><div className="panel-title"><div><h2>Gastos recientes</h2><p>Últimos egresos registrados.</p></div></div>{data.expenses.map((expense)=><div className="expense-row" key={String(expense.id)}><div><strong>{String(expense.description)}</strong><small>{String(expense.category)} · {String(expense.method)}{expense.vendor?` · ${String(expense.vendor)}`:""}</small></div><b className="negative">-{money(Number(expense.amountCents))}</b></div>)}{!data.expenses.length&&<Empty text="Aún no hay gastos."/>}</section></div>}

function RefundPanel({data,saving,request,onMessage,onPaymentChanged}:{data:CommerceData;saving:boolean;request:(payload:Record<string,unknown>)=>Promise<Record<string,unknown>>;onMessage:(value:string)=>void;onPaymentChanged:(appointmentId:string,paidCents:number)=>void}){const [target,setTarget]=useState("");const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const [kind,id]=target.split(":");if(!id)return;try{const body=await request({action:"refund",paymentId:kind==="payment"?id:undefined,saleId:kind==="sale"?id:undefined,amountCents:cents(form.get("amount")),reason:form.get("reason")});if(typeof body.appointmentId==="string"&&typeof body.paidCents==="number")onPaymentChanged(body.appointmentId,body.paidCents);event.currentTarget.reset();setTarget("");onMessage("Reembolso registrado.")}catch{}};return <div className="commerce-grid"><form className="panel expense-form" onSubmit={submit}><div className="panel-title"><div><h2>Procesar reembolso</h2><p>Selecciona un cobro y registra el motivo.</p></div><RotateCcw size={20}/></div><label>Operación<select value={target} onChange={(event)=>setTarget(event.target.value)} required><option value="">Selecciona...</option>{data.payments.filter((payment)=>Number(payment.refundableCents)>0).map((payment)=><option key={String(payment.id)} value={`payment:${String(payment.id)}`}>{String(payment.clientName)} · {String(payment.serviceName)} · disponible {money(Number(payment.refundableCents))}</option>)}{data.sales.map((sale)=><option key={String(sale.id)} value={`sale:${String(sale.id)}`}>Venta {String(sale.receiptNumber)} · disponible {money(Number(sale.totalCents)+Number(sale.tipCents||0))}</option>)}</select></label><label>Monto<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Motivo<textarea name="reason" maxLength={240} required placeholder="Ej. Servicio no realizado"/></label><button className="primary" disabled={saving||!target}>{saving?"Procesando...":"Confirmar reembolso"}</button></form><section className="panel expense-list"><div className="panel-title"><div><h2>Historial de reembolsos</h2><p>Movimientos con trazabilidad.</p></div></div>{data.refunds.map((refund)=><div className="expense-row" key={String(refund.id)}><div><strong>{String(refund.clientName)} · {String(refund.itemName)}</strong><small>{String(refund.reason)} · {String(refund.method)}</small></div><b className="negative">-{money(Number(refund.amountCents))}</b></div>)}{!data.refunds.length&&<Empty text="Aún no hay reembolsos."/>}</section></div>}

function ReceiptPanel({appointments,sales}:{appointments:CashAppointment[];sales:Record<string,unknown>[]}){return <div className="panel receipt-panel"><div className="panel-title"><div><h2>Recibos</h2><p>Abre una versión lista para imprimir o guardar como PDF.</p></div><Printer size={20}/></div><div className="receipt-list">{appointments.filter((appointment)=>appointment.paidCents>0).slice(0,30).map((appointment)=><div className="receipt-row" key={appointment.id}><div><strong>{appointment.clientName}</strong><small>{appointment.serviceName} · {appointment.date} · {money(appointment.paidCents)}</small></div><a className="secondary compact" href={`/api/admin/receipts?appointmentId=${encodeURIComponent(appointment.id)}`} target="_blank" rel="noreferrer"><Printer size={14}/> Imprimir</a></div>)}{sales.slice(0,30).map((sale)=><div className="receipt-row" key={String(sale.id)}><div><strong>Venta {String(sale.receiptNumber)}</strong><small>{String(sale.clientName||"Cliente mostrador")} · {money(Number(sale.totalCents)+Number(sale.tipCents||0))}</small></div><a className="secondary compact" href={`/api/admin/receipts?saleId=${encodeURIComponent(String(sale.id))}`} target="_blank" rel="noreferrer"><Printer size={14}/> Imprimir</a></div>)}{!appointments.some((appointment)=>appointment.paidCents>0)&&!sales.length&&<Empty text="Los recibos aparecerán después de cobrar."/>}</div></div>}

function ProductModal({product,saving,onClose,onSubmit}:{product?:Product;saving:boolean;onClose:()=>void;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="modal-head"><div><span className="eyebrow">Catálogo POS</span><h2>{product?"Editar producto":"Nuevo producto"}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><div className="form-grid"><label>Nombre<input name="name" defaultValue={product?.name} required/></label><label>SKU<input name="sku" defaultValue={product?.sku}/></label><label>Categoría<input name="category" defaultValue={product?.category??"General"}/></label><label>Precio<input name="price" type="number" min="0.01" step="0.01" defaultValue={product?product.priceCents/100:undefined} required/></label><label>Costo<input name="cost" type="number" min="0" step="0.01" defaultValue={product?product.costCents/100:0}/></label><label>Stock inicial{product?<input value={product.stockQuantity} disabled/>:<input name="stock" type="number" min="0" step="1" defaultValue="0"/>}</label><label>Mínimo<input name="minimum" type="number" min="0" step="1" defaultValue={product?.minimumStock??2}/></label>{product&&<label className="checkbox-field"><input name="active" type="checkbox" defaultChecked={product.active!==0}/><span><b>Producto activo</b><small>Los productos inactivos no aparecen en el POS.</small></span></label>}</div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando...":product?"Guardar cambios":"Crear producto"}</button></div></form></div>}
function AdjustModal({product,saving,onClose,onSubmit}:{product:Product;saving:boolean;onClose:()=>void;onSubmit:(delta:number,type:string,note:string)=>Promise<void>}){const [type,setType]=useState("entrada");const [quantity,setQuantity]=useState("1");return <div className="modal-backdrop"><form className="modal" onSubmit={(event)=>{event.preventDefault();void onSubmit(Number(quantity),type,String(new FormData(event.currentTarget).get("note")||""))}}><div className="modal-head"><div><span className="eyebrow">Inventario</span><h2>Ajustar {product.name}</h2><p>Stock actual: {product.stockQuantity}</p></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><div className="form-grid"><label>Movimiento<select value={type} onChange={(event)=>setType(event.target.value)}><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="ajuste">Fijar existencia</option></select></label><label>{type==="ajuste"?"Nueva existencia":"Cantidad"}<input value={quantity} onChange={(event)=>setQuantity(event.target.value)} type="number" min="0" step="1" required/></label><label className="wide">Nota<input name="note" maxLength={300}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando...":"Aplicar ajuste"}</button></div></form></div>}
function Empty({text}:{text:string}){return <div className="commerce-empty">{text}</div>}
function parseData(value:unknown):CommerceData{if(!isJsonObject(value))throw new Error("La respuesta comercial no es válida.");const arrays=["products","movements","expenses","sales","refunds","payments"] as const;if(arrays.some((key)=>!Array.isArray(value[key])))throw new Error("La respuesta comercial está incompleta.");return {products:value.products as Product[],movements:value.movements as Record<string,unknown>[],expenses:value.expenses as Record<string,unknown>[],sales:value.sales as Record<string,unknown>[],refunds:value.refunds as Record<string,unknown>[],payments:value.payments as Record<string,unknown>[],summary:(value.summary||{}) as Record<string,number>,canManage:value.canManage!==false}}
function cents(value:FormDataEntryValue|null){const amount=Number(value);return Number.isFinite(amount)&&amount>=0?Math.round(amount*100):0}
function whole(value:FormDataEntryValue|null){const amount=Number(value);return Number.isSafeInteger(amount)&&amount>=0?amount:0}
function money(value:number){return new Intl.NumberFormat("es-VE",{style:"currency",currency:"USD"}).format(value/100)}
