"use client";

import { useEffect, useState } from "react";
import { apiError, isJsonObject, readJsonObject } from "./api-json";
import { confirmAction } from "./dialogs";
import { Armchair, CheckCircle2, Pencil, Plus, Trash2, Wrench, X } from "lucide-react";

type Option = { id:string; name:string; serviceIds?:string[] };
type Resource = { id:string; name:string; kind:string; notes:string; serviceIds:string[]; professionalIds:string[]; active:boolean; appointmentCount:number; createdAt:string; updatedAt:string };

const kindLabels:Record<string,string> = { station:"Estación", equipment:"Equipo", room:"Sala", other:"Otro" };

function isResource(value:unknown):value is Resource {
  return isJsonObject(value) && ["id","name","kind","notes","createdAt","updatedAt"].every((key)=>typeof value[key]==="string") &&
    ["serviceIds","professionalIds"].every((key)=>Array.isArray(value[key])&&value[key].every((item)=>typeof item === "string")) &&
    typeof value.active === "boolean" && typeof value.appointmentCount === "number";
}

export function ResourcesManager({ services, professionals }:{services:Option[];professionals:Option[]}) {
  const [resources,setResources]=useState<Resource[]>([]); const [canManage,setCanManage]=useState(false); const [loading,setLoading]=useState(true);
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [editing,setEditing]=useState<Resource|null|"new">(null);
  useEffect(()=>{let mounted=true;fetch("/api/admin/resources",{credentials:"same-origin"}).then(async(response)=>{const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos cargar los recursos"));if(mounted){setResources(Array.isArray(body.resources)?body.resources.filter(isResource):[]);setCanManage(body.canManage===true)}}).catch((reason)=>{if(mounted)setError(reason instanceof Error?reason.message:"No pudimos cargar los recursos")}).finally(()=>{if(mounted)setLoading(false)});return()=>{mounted=false}},[]);
  const saved=(resource:Resource)=>{setResources((items)=>{const exists=items.some((item)=>item.id===resource.id);return exists?items.map((item)=>item.id===resource.id?resource:item):[...items,resource]});setEditing(null);setNotice("Recurso guardado correctamente.");window.setTimeout(()=>setNotice(""),2400)};
  const removed=(id:string)=>{setResources((items)=>items.filter((item)=>item.id!==id));setEditing(null);setNotice("Recurso eliminado.");window.setTimeout(()=>setNotice(""),2400)};
  return <div className="resources-stack">
    {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-success"><CheckCircle2 size={15}/>{notice}</p>}
    <section className="panel resources-panel"><div className="resources-toolbar"><div><span className="eyebrow">Operación física</span><h2>Estaciones y recursos</h2><p>Asigna sillas, salas o equipos a servicios y profesionales para evitar usos incompatibles.</p></div>{canManage&&<button className="primary" onClick={()=>setEditing("new")}><Plus size={16}/> Nuevo recurso</button>}</div>
      {loading?<div className="loading-line"/>:<div className="resources-grid">{resources.map((resource)=><article className={`resource-card ${resource.active?"":"inactive"}`} key={resource.id}><div className="resource-icon">{resource.kind==="equipment"?<Wrench size={19}/>:<Armchair size={19}/>}</div><div className="resource-copy"><div className="resource-title"><h3>{resource.name}</h3><span className={`status ${resource.active?"confirmada":"programada"}`}>{resource.active?"Activo":"Inactivo"}</span></div><p>{kindLabels[resource.kind]??"Recurso"}{resource.notes?` · ${resource.notes}`:""}</p><small>{resource.serviceIds.length||"Ningún"} servicio(s) · {resource.professionalIds.length||"Todo el"} profesional(es) · {resource.appointmentCount} citas vinculadas</small></div>{canManage&&<div className="resource-actions"><button className="ghost-icon" aria-label={`Editar ${resource.name}`} onClick={()=>setEditing(resource)}><Pencil size={15}/></button>{resource.appointmentCount===0&&<button className="ghost-icon danger" aria-label={`Eliminar ${resource.name}`} onClick={()=>setEditing(resource)}><Trash2 size={15}/></button>}</div>}</article>)}{!resources.length&&<div className="resources-empty"><Armchair size={24}/><strong>No hay estaciones ni recursos.</strong><span>Crea el primero para controlar la capacidad física de tu negocio.</span></div>}</div>}
    </section>
    {editing&&<ResourceModal resource={editing==="new"?null:editing} services={services} professionals={professionals} onClose={()=>setEditing(null)} onSaved={saved} onDeleted={removed}/>} 
  </div>;
}

function ResourceModal({resource,services,professionals,onClose,onSaved,onDeleted}:{resource:Resource|null;services:Option[];professionals:Option[];onClose:()=>void;onSaved:(resource:Resource)=>void;onDeleted:(id:string)=>void}) {
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);const serviceIds=services.map((item)=>item.id).filter((id)=>form.get(`service-${id}`)==="on");const professionalIds=professionals.map((item)=>item.id).filter((id)=>form.get(`professional-${id}`)==="on");const payload={id:resource?.id,name:form.get("name"),kind:form.get("kind"),notes:form.get("notes"),serviceIds,professionalIds,active:form.get("active")==="on"};try{const response=await fetch("/api/admin/resources",{method:resource?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos guardar el recurso"));if(!isResource(body.resource))throw new Error("El recurso guardado no es válido.");onSaved(body.resource)}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos guardar el recurso");setSaving(false)}};
  const remove=async()=>{if(!resource||resource.appointmentCount>0)return;
    if(!await confirmAction({title:`¿Eliminar ${resource.name}?`,message:"La estación deja de estar disponible para asignar en las citas.",destructive:true,confirmLabel:"Eliminar estación"}))return;setSaving(true);setError("");try{const response=await fetch("/api/admin/resources",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:resource.id})});const body=await readJsonObject(response);if(!response.ok)throw new Error(apiError(body,"No pudimos eliminar el recurso"));onDeleted(resource.id)}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos eliminar el recurso");setSaving(false)}};
  return <div className="modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><div className="modal resource-modal" role="dialog" aria-modal="true" aria-labelledby="resource-form-title"><div className="modal-head"><div><span className="eyebrow">Capacidad del local</span><h2 id="resource-form-title">{resource?"Editar recurso":"Nuevo recurso"}</h2></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X/></button></div><form onSubmit={submit}><div className="form-grid"><label className="wide">Nombre<input name="name" required minLength={2} maxLength={100} defaultValue={resource?.name??""} placeholder="Silla principal, lavacabezas..."/></label><label>Tipo<select name="kind" defaultValue={resource?.kind??"station"}><option value="station">Estación</option><option value="equipment">Equipo</option><option value="room">Sala</option><option value="other">Otro</option></select></label><label>Notas<input name="notes" maxLength={300} defaultValue={resource?.notes??""} placeholder="Opcional"/></label><fieldset className="wide resource-picker"><legend>Servicios compatibles</legend>{services.map((item)=><label key={item.id}><input type="checkbox" name={`service-${item.id}`} defaultChecked={resource?resource.serviceIds.includes(item.id):true}/><span>{item.name}</span></label>)}{!services.length&&<p>Crea servicios para poder vincularlos.</p>}</fieldset><fieldset className="wide resource-picker"><legend>Profesionales compatibles</legend>{professionals.map((item)=><label key={item.id}><input type="checkbox" name={`professional-${item.id}`} defaultChecked={resource?resource.professionalIds.includes(item.id):true}/><span>{item.name}</span></label>)}{!professionals.length&&<p>Crea profesionales para poder vincularlos.</p>}</fieldset><label className="checkbox-field"><input name="active" type="checkbox" defaultChecked={resource?resource.active:true}/><span><b>Recurso activo</b><small>Disponible para nuevas asignaciones.</small></span></label></div>{resource&&resource.appointmentCount>0&&<p className="client-delete-note">Tiene {resource.appointmentCount} citas vinculadas; no se puede eliminar, solo desactivar.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions split">{resource&&resource.appointmentCount===0?<button type="button" className="danger-button" disabled={saving} onClick={()=>void remove()}><Trash2 size={15}/> Eliminar</button>:<span/>}<div><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando...":"Guardar recurso"}</button></div></div></form></div></div>;
}
